/* flow_signal_router.js - TRAVEL_V1_M2M_CONTROLLER_CLEAN_V1 */
(function(){
 if(window.KRXA_M2M_CONTROLLER_CLEAN_V1_LOADED)return; window.KRXA_M2M_CONTROLLER_CLEAN_V1_LOADED=true;
 if(typeof window.KRXA_PAGE5_AI_DIALOGUE_ENABLED!=='boolean')window.KRXA_PAGE5_AI_DIALOGUE_ENABLED=false;
 if(typeof window.KRXA_MINI_AI_DIALOGUE_ENABLED!=='boolean')window.KRXA_MINI_AI_DIALOGUE_ENABLED=false;
 var state={lastFlow:null,source:null,running:false}; window.KRXA_FLOW_STATE=state;
 function txt(el){try{return(el&&(el.innerText||el.textContent||''))||'';}catch(e){return'';}}
 function log(id,p){try{console.log('[M2M_CONTROLLER_CLEAN_V1]',id,p||'');}catch(e){}}
 function release(){try{state.running=false;window.KRXA_M2M_BUSY=false;window.KRXA_AI_DIALOGUE_BUSY=false;window.KRXA_AI_DIALOGUE_LISTENING=false;document.body.classList.remove('busy','listening','locked','modal-open');document.querySelectorAll('[disabled]').forEach(function(el){if(el.getAttribute('data-keep-disabled')!=='1')el.removeAttribute('disabled');});}catch(e){}}
 function unlock(){try{window.KRXA_TTS_UNLOCKED=true;if(window.speechSynthesis){var u=new SpeechSynthesisUtterance(' ');u.volume=.01;window.speechSynthesis.speak(u);setTimeout(function(){try{window.speechSynthesis.cancel();}catch(e){}},50);}}catch(e){}}
 function visual(el,on){try{if(!el)return;el.classList.toggle('active',!!on);el.classList.toggle('on',!!on);el.setAttribute('data-ai',on?'on':'off');el.setAttribute('aria-checked',on?'true':'false');if(txt(el).indexOf('AI')>=0)el.textContent=on?'AI ON':'AI OFF';}catch(e){}}
 function page5On(){try{if(window.KRXA_PAGE5_M2M_STATE_MACHINE&&typeof window.KRXA_PAGE5_M2M_STATE_MACHINE.getMode==='function'){var m=window.KRXA_PAGE5_M2M_STATE_MACHINE.getMode();if(m==='ai_dialogue'||m==='ai')return true;}}catch(e){}try{var el=document.getElementById('autoToggle');if(el&&(el.classList.contains('active')||el.classList.contains('on')||el.getAttribute('data-ai')==='on'||el.getAttribute('aria-checked')==='true'))return true;}catch(e){}return window.KRXA_PAGE5_AI_DIALOGUE_ENABLED===true;}
 function miniOn(){try{var el=document.querySelector("[data-flow='mini.ai.toggle']");if(el&&(el.classList.contains('active')||el.classList.contains('on')||el.getAttribute('data-ai')==='on'||el.getAttribute('aria-checked')==='true'))return true;}catch(e){}return window.KRXA_MINI_AI_DIALOGUE_ENABLED===true;}
 function setPage5(on,el){window.KRXA_PAGE5_AI_DIALOGUE_ENABLED=!!on;window.KRXA_AI_DIALOGUE_ENABLED=!!on;window.KRXA_PAGE5_MODE=on?'ai':'translate';window.KRXA_M2M_MODE=window.KRXA_PAGE5_MODE;try{if(window.KRXA_PAGE5_M2M_STATE_MACHINE&&typeof window.KRXA_PAGE5_M2M_STATE_MACHINE.setMode==='function')window.KRXA_PAGE5_M2M_STATE_MACHINE.setMode(on?'ai_dialogue':'translate');}catch(e){}visual(el||document.getElementById('autoToggle'),!!on);}
 function setMini(on,el){window.KRXA_MINI_AI_DIALOGUE_ENABLED=!!on;visual(el||document.querySelector("[data-flow='mini.ai.toggle']"),!!on);}
 function runT(src,flow){unlock();release();state.running=true;try{if(window.KRXA_Translate&&typeof window.KRXA_Translate.requestMicAndStart==='function')return window.KRXA_Translate.requestMicAndStart({source:src,flow_id:flow,userTriggered:true,forceTranslate:true,mode:'translate'});}catch(e){console.warn('[M2M CLEAN translate failed]',e);}release();return false;}
 function runA(src,flow){unlock();release();state.running=true;try{if(window.KRXA_AI_DIALOGUE&&typeof window.KRXA_AI_DIALOGUE.speakOnce==='function')return window.KRXA_AI_DIALOGUE.speakOnce({source:src,flow_id:flow,userTriggered:true});}catch(e){console.warn('[M2M CLEAN ai failed]',e);}release();return false;}
 function speak(src){if(src==='page5')return page5On()?runA('M2M_CONTROLLER_CLEAN_V1_PAGE5_AI','page5.m2m.speak'):runT('M2M_CONTROLLER_CLEAN_V1_PAGE5_TRANSLATE','page5.m2m.speak'); if(src==='mini')return miniOn()?runA('M2M_CONTROLLER_CLEAN_V1_MINI_AI','mini.m2m.speak'):runT('M2M_CONTROLLER_CLEAN_V1_MINI_TRANSLATE','mini.m2m.speak'); return txt(document.body).indexOf('말대말 통역')>=0?speak('page5'):speak('mini');}
 function stop(){try{if(window.KRXA_AI_DIALOGUE&&typeof window.KRXA_AI_DIALOGUE.stop==='function')window.KRXA_AI_DIALOGUE.stop();}catch(e){}try{if(window.KRXA_Translate&&typeof window.KRXA_Translate.stopAuto==='function')window.KRXA_Translate.stopAuto();}catch(e){}try{if(window.speechSynthesis)window.speechSynthesis.cancel();}catch(e){}release();return true;}
 function ensureMini(){try{if(document.querySelector("[data-flow='mini.ai.toggle']"))return;if(txt(document.body).indexOf('말대말 통역')>=0)return;var bars=Array.from(document.querySelectorAll('button,div,a')).filter(function(el){var t=txt(el);return t.indexOf('말대말')>=0||t.indexOf('말하면 바로 통역')>=0;});var bar=bars[bars.length-1];if(!bar)return;bar.setAttribute('data-flow','mini.m2m.speak');if(getComputedStyle(bar).position==='static')bar.style.position='relative';var b=document.createElement('span');b.setAttribute('data-flow','mini.ai.toggle');b.setAttribute('data-ai','off');b.setAttribute('aria-checked','false');b.textContent='AI OFF';b.style.cssText='position:absolute;right:12px;top:6px;font-size:11px;padding:2px 7px;border-radius:999px;background:#dbe3ef;color:#0f172a;font-weight:800;z-index:9;';b.addEventListener('click',function(ev){ev.preventDefault();ev.stopPropagation();if(ev.stopImmediatePropagation)ev.stopImmediatePropagation();setMini(!miniOn(),b);b.textContent=miniOn()?'AI ON':'AI OFF';b.style.background=miniOn()?'#2563eb':'#dbe3ef';b.style.color=miniOn()?'#fff':'#0f172a';return false;},true);bar.appendChild(b);}catch(e){}}
 function go(id,p){log(id,p);state.lastFlow=id;if(id==='page5.ai.toggle'){setPage5(!page5On(),p&&p.target);return true;}if(id==='mini.ai.toggle'){setMini(!miniOn(),p&&p.target);return true;}if(id==='page5.m2m.speak')return speak('page5');if(id==='mini.m2m.speak')return speak('mini');if(id==='m2m.speak')return speak();if(id==='m2m.stop')return stop();if(id==='modal.close'){try{if(window.KRXA_App&&window.KRXA_App.closeModal)window.KRXA_App.closeModal();}catch(e){}release();return true;}if(id==='page.back'){stop();try{if(window.KRXA_App&&window.KRXA_App.goUserPage){window.KRXA_App.goUserPage(2);return true;}}catch(e){}return false;}if(id==='m2m.text.open'){try{if(window.KRXA_Translate&&window.KRXA_Translate.openQuickInput){window.KRXA_Translate.openQuickInput();return true;}}catch(e){}}if(id==='m2m.replay'){try{if(window.KRXA_Translate&&window.KRXA_Translate.replayTTS){window.KRXA_Translate.replayTTS();return true;}}catch(e){}}return false;}
 function onClick(ev){var el=null;try{el=ev.target&&ev.target.closest?ev.target.closest('[data-flow]'):null;}catch(e){}if(!el)return;var id=el.getAttribute('data-flow');if(!id)return;ev.preventDefault();ev.stopPropagation();if(ev.stopImmediatePropagation)ev.stopImmediatePropagation();go(id,{target:el,text:txt(el)});return false;}
 function init(){if(window.KRXA_M2M_CONTROLLER_CLEAN_V1_BOUND)return;window.KRXA_M2M_CONTROLLER_CLEAN_V1_BOUND=true;document.addEventListener('click',onClick,true);setTimeout(ensureMini,300);setTimeout(ensureMini,1000);setInterval(ensureMini,2500);}
 document.addEventListener('DOMContentLoaded',function(){setTimeout(init,30);});setTimeout(init,200);
 window.KRXA_FLOW={go:go,init:init,state:state,forceReleaseUI:release,unlockMobileTTS:unlock};
 window.M2M_CONTROLLER={speak:speak,stopAll:stop,page5AiOn:page5On,miniAiOn:miniOn,setPage5Ai:setPage5,setMiniAi:setMini};
})();
